### ISSUE TITLE
Build: Custom full-static (static-CRT) SFML

### ISSUE THREAD

**Issue by xparq** [xparq/Out_of_Nothing#247]
The goal is to get the current sources from [SFML-master](https://github.com/SFML/SFML/archive/refs/heads/master.zip), unpack, and build _truly_ static SFML libs (compiled with `-MT` and `-MTd`). Without cmake, preferably.

- In extern, similarly to TOML++
  - [x] Yeah, no... I've created a GH repo for it (see later below).
- [x] And then also to SFW...
  - [x] No, that should be part of the upstream build process! (xparq/sfw#353, xparq/sfw#354)
    -> And it should publish prebuilt libs as GH Releases (xparq/sfw#357)
  - [ ] And remove the SFW libs from the OON repo (to not bloat it)!
    _Except... no: unfortunately, the GHA build can't produce those libs all by itself! :-/_
- [ ] OON should also have a similar custom-libs downloader (as the one for stock SFML), like xparq/sfw#353
- [x] And zstd... _(I've already had a static-CRT version of it prepared, thankfully, with a simple build script to create it.)_
  - [x] But then I've improved that script quite a bit, so it's less of a nuisance to use.
  - [x] _Also, it was not documented why a custom build of zstd is needed at all! (Because the stock pre-built has the unresolved `___chkstk_ms` symbol... [Probably because it wasn't compiled with MSVC, but e.g. MinGW](https://github.com/lz4/lz4/issues/920#issuecomment-1124003558).)_
- [x] Then finally build and test a fully static exe!
  - Wow, I actually started with this first (obviously, after getting SFML & its deps. + SFW compiled with -MT -- _which took an hour or two, but my BB makefile fared pretty well_).
    **It's lovely! The exe size haven't even increased noticeably! :-o** 
    At first I saw a strange FPS anomaly with the first successful `nbuild` exe (a pretty significant FPS drop, around 25%), which would likely have been a showstopper, but then I couldn't reproduce that a few rebuilds later (that were necessary for supposedly unrelated reasons).

- [x] Adding a custom build scaffolding for SFML-MT sounds all nice, but even nicer would be a stronger baseline control, and preserving -- and then also offering! -- the actual binaries. _But not in this same repo, to avoid even more bloat; it's already 25 MB for almost nothing! :-/_
  - [x] Created repo [x1ab/SFML-staticCRT-build](https://github.com/x1ab/SFML-staticCRT-build/)
    - [x] And a baseline [SFML/MT release for 7c9e7aa](https://github.com/x1ab/SFML-staticCRT-build/releases/tag/SFML-master-7c9e7aa)
    - [x] And a canonical download URL: https://x1ab.github.io/download/SFML/3.0-pre/custom/

----
- [ ] Alas, can't remove the -MD libs, for the GHA can only build with the stock SFML yet! :-/
